// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//* Config Imports
import "dotenv/config";

//* Prisma Imports
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
